[env:bbq20kbd_breakout]
platform = wizio-RPI
framework = Pico-SDK-CMAKE
board = bbq20kbd_breakout

custom_cmake =
	-D VARIANT_DIR=bbq20kbd_breakout
	-D PICO_PLATFORM=rp2040
	;-D CMAKE_BUILD_TYPE=Debug

#custom_ninja = -v
